version: '3.9'
services:
  db:
    container_name: rails
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=swift
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "54320:5432"

  app:
    container_name: rails
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=swift
      - JWT_SECRET=random12344
      - JWT_EXPIRATION=1h
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_API_KEY=admin

    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  db:
    driver: local
