version: '3.9'
services:

  app:
    container_name: rails
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=trainn
      - JWT_SECRET=random12344
      - JWT_EXPIRATION=1h
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - ADMIN_API_KEY=admin

    depends_on:
      - db
    volumes:
      - .:/usr/src/app

    networks:
      - postgres

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=trainn
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres



volumes:
  db:
    driver: local

networks:
  postgres:
    driver: bridge
